### PR TITLE
Elasticsearch support

### PR DESCRIPTION
**Pull request by ychaker**
# Acceptance criteria

- [x] user can switch between Solr and ES on start page
- [x] user sees ACE UI editor with JSON support for ES
- [x] user can run a search pointing to ES
- [x] user click on logo (navigates back to start page), proper ES URL and query are in the URL params
- [x] user can specify fields to show in ES via the `fl` params in the ES URL
- [ ] user can run an explain other search for ES

### CODE REVIEW

**Comment by softwaredoug** [comment]
Christmas in February!

**Comment by softwaredoug** [comment]
I feel like this is still in progress, noting several rough edges as I go through the Elasticsearch user experience:

1. Its a bit confusing when last time you were doing Elasticsearch and you hit the "Solr" tab. The URL is identical. So you see the ES URL in the Solr tab. Should we store two sets of settings instead of a single set?

image

I'm launching an incognito window as to not have any existing experimental Elasticsearch localparams settings around. Here's what I see:

1. The placeholder URL for ES is not a valid ES URL. Change to `http://localhost:9200/indexname/_search`


2. I think it would be good to initialize the query for Elasticsearch to 

```json
{
   "query": {
     "match": {
         "_all": "text"
      }
   }
}
```

image

3. Starting with that query, and URL `http://es.quepid.com/statedecoded/_search` I recieve the following results (notice the `[object Object]`). Also should `_explanation` be here?

image

4. Errors prompt me to view the Solr response. We should get ES errors back, can we display those?

image

5. Clicking the "<Number> total response" link goes back to the Splainer page,  doesn't go somewhere I can browse the results

6. We need to update the documentation ("take a tour" link) that shows people what to do

7. The explain-other form is the width of the modal, its not clear its a text entry box/button

image

8. Running Explain other gave me the following error

image

**Comment by ychaker** [comment]
@softwaredoug should we tick off the things from the acceptance criteria that are done?

I like the changes you made, so 👍  to moving forward!

**Comment by softwaredoug** [comment]
We have all this but I want to disable the explain other for now

**Pull request merged**
